/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const IncidentId = IDL.Nat;
export const TaskId = IDL.Nat;
export const Location = IDL.Record({
  'region' : IDL.Text,
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const AlertId = IDL.Nat;
export const VolunteerMessage = IDL.Record({
  'message' : IDL.Text,
  'recipientId' : UserId,
});
export const TaskAssignment = IDL.Record({
  'id' : TaskId,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'incidentId' : IncidentId,
  'assignedTo' : UserId,
  'resourcesAllocated' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Alert = IDL.Record({
  'id' : AlertId,
  'affectedAreas' : IDL.Vec(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'severity' : Severity,
  'location' : Location,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const IncidentReport = IDL.Record({
  'id' : IncidentId,
  'status' : IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'description' : IDL.Text,
  'reporterId' : UserId,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'severity' : Severity,
  'photo' : IDL.Opt(ExternalBlob),
  'location' : Location,
});
export const RecoveryProgress = IDL.Record({
  'region' : IDL.Text,
  'pendingNeeds' : IDL.Text,
  'overallPercentage' : IDL.Nat,
  'infrastructure' : IDL.Nat,
  'services' : IDL.Nat,
  'population' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'citizen' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'location' : Location,
});
export const Volunteer = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'approved' : IDL.Bool,
  'phone' : IDL.Text,
});
export const EmergencyContact = IDL.Record({
  'region' : IDL.Text,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'read' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ResourceInventory = IDL.Record({
  'vehicles' : IDL.Nat,
  'food' : IDL.Nat,
  'medicine' : IDL.Nat,
  'personnel' : IDL.Nat,
  'water' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addEmergencyContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addNotification' : IDL.Func([UserId, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignTask' : IDL.Func([IncidentId, UserId, IDL.Text], [TaskId], []),
  'clearVolunteerMessage' : IDL.Func([UserId], [], []),
  'createAlert' : IDL.Func(
      [Location, IDL.Text, Severity, IDL.Text, IDL.Vec(IDL.Text)],
      [AlertId],
      [],
    ),
  'fetchVolunteerMessage' : IDL.Func(
      [],
      [IDL.Opt(VolunteerMessage)],
      ['query'],
    ),
  'getActiveTasks' : IDL.Func([], [IDL.Vec(TaskAssignment)], ['query']),
  'getAlertsByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Alert)], ['query']),
  'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllIncidentReports' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
  'getAllRecoveryProgress' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, RecoveryProgress))],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
  'getCallerAssignedTasks' : IDL.Func([], [IDL.Vec(TaskAssignment)], ['query']),
  'getCallerIncidentReports' : IDL.Func(
      [],
      [IDL.Vec(IncidentReport)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getEmergencyContactsByRegion' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EmergencyContact)],
      ['query'],
    ),
  'getIncidentReport' : IDL.Func([IncidentId], [IncidentReport], ['query']),
  'getNotificationsForUser' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPersistentICRole' : IDL.Func([], [UserRole], ['query']),
  'getRegionRecoveryProgress' : IDL.Func(
      [IDL.Text],
      [RecoveryProgress],
      ['query'],
    ),
  'getResourceInventory' : IDL.Func([], [ResourceInventory], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getVolunteer' : IDL.Func([IDL.Text], [IDL.Opt(Volunteer)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'registerCitizen' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Location, IDL.Text],
      [],
      [],
    ),
  'registerVolunteer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'registerWithRole' : IDL.Func([UserRole], [], []),
  'reportIncident' : IDL.Func(
      [Location, IDL.Text, Severity, IDL.Text, IDL.Opt(ExternalBlob)],
      [IncidentId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendVolunteerMessage' : IDL.Func([UserId, IDL.Text], [], []),
  'updateIncidentStatus' : IDL.Func(
      [
        IncidentId,
        IDL.Variant({
          'resolved' : IDL.Null,
          'open' : IDL.Null,
          'inProgress' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateRecoveryProgress' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateResourceInventory' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateTaskStatus' : IDL.Func(
      [
        TaskId,
        IDL.Variant({
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'inProgress' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateVolunteerApproval' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'validateCitizenLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'validateVolunteerLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const IncidentId = IDL.Nat;
  const TaskId = IDL.Nat;
  const Location = IDL.Record({
    'region' : IDL.Text,
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const AlertId = IDL.Nat;
  const VolunteerMessage = IDL.Record({
    'message' : IDL.Text,
    'recipientId' : UserId,
  });
  const TaskAssignment = IDL.Record({
    'id' : TaskId,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'incidentId' : IncidentId,
    'assignedTo' : UserId,
    'resourcesAllocated' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Alert = IDL.Record({
    'id' : AlertId,
    'affectedAreas' : IDL.Vec(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'severity' : Severity,
    'location' : Location,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const IncidentReport = IDL.Record({
    'id' : IncidentId,
    'status' : IDL.Variant({
      'resolved' : IDL.Null,
      'open' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'description' : IDL.Text,
    'reporterId' : UserId,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'severity' : Severity,
    'photo' : IDL.Opt(ExternalBlob),
    'location' : Location,
  });
  const RecoveryProgress = IDL.Record({
    'region' : IDL.Text,
    'pendingNeeds' : IDL.Text,
    'overallPercentage' : IDL.Nat,
    'infrastructure' : IDL.Nat,
    'services' : IDL.Nat,
    'population' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'citizen' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'location' : Location,
  });
  const Volunteer = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'approved' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const EmergencyContact = IDL.Record({
    'region' : IDL.Text,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'read' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ResourceInventory = IDL.Record({
    'vehicles' : IDL.Nat,
    'food' : IDL.Nat,
    'medicine' : IDL.Nat,
    'personnel' : IDL.Nat,
    'water' : IDL.Nat,
  });
  
  return IDL.Service({
    'addEmergencyContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addNotification' : IDL.Func([UserId, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignTask' : IDL.Func([IncidentId, UserId, IDL.Text], [TaskId], []),
    'clearVolunteerMessage' : IDL.Func([UserId], [], []),
    'createAlert' : IDL.Func(
        [Location, IDL.Text, Severity, IDL.Text, IDL.Vec(IDL.Text)],
        [AlertId],
        [],
      ),
    'fetchVolunteerMessage' : IDL.Func(
        [],
        [IDL.Opt(VolunteerMessage)],
        ['query'],
      ),
    'getActiveTasks' : IDL.Func([], [IDL.Vec(TaskAssignment)], ['query']),
    'getAlertsByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Alert)], ['query']),
    'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllIncidentReports' : IDL.Func(
        [],
        [IDL.Vec(IncidentReport)],
        ['query'],
      ),
    'getAllRecoveryProgress' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, RecoveryProgress))],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
    'getCallerAssignedTasks' : IDL.Func(
        [],
        [IDL.Vec(TaskAssignment)],
        ['query'],
      ),
    'getCallerIncidentReports' : IDL.Func(
        [],
        [IDL.Vec(IncidentReport)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getEmergencyContactsByRegion' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EmergencyContact)],
        ['query'],
      ),
    'getIncidentReport' : IDL.Func([IncidentId], [IncidentReport], ['query']),
    'getNotificationsForUser' : IDL.Func(
        [],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPersistentICRole' : IDL.Func([], [UserRole], ['query']),
    'getRegionRecoveryProgress' : IDL.Func(
        [IDL.Text],
        [RecoveryProgress],
        ['query'],
      ),
    'getResourceInventory' : IDL.Func([], [ResourceInventory], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getVolunteer' : IDL.Func([IDL.Text], [IDL.Opt(Volunteer)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'registerCitizen' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Location, IDL.Text],
        [],
        [],
      ),
    'registerVolunteer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'registerWithRole' : IDL.Func([UserRole], [], []),
    'reportIncident' : IDL.Func(
        [Location, IDL.Text, Severity, IDL.Text, IDL.Opt(ExternalBlob)],
        [IncidentId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendVolunteerMessage' : IDL.Func([UserId, IDL.Text], [], []),
    'updateIncidentStatus' : IDL.Func(
        [
          IncidentId,
          IDL.Variant({
            'resolved' : IDL.Null,
            'open' : IDL.Null,
            'inProgress' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateRecoveryProgress' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateResourceInventory' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateTaskStatus' : IDL.Func(
        [
          TaskId,
          IDL.Variant({
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'inProgress' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateVolunteerApproval' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'validateCitizenLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'validateVolunteerLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };