/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : AlertId,
  'affectedAreas' : Array<string>,
  'message' : string,
  'timestamp' : bigint,
  'category' : string,
  'severity' : Severity,
  'location' : Location,
}
export type AlertId = bigint;
export interface EmergencyContact {
  'region' : string,
  'contactInfo' : string,
  'name' : string,
}
export type ExternalBlob = Uint8Array;
export type IncidentId = bigint;
export interface IncidentReport {
  'id' : IncidentId,
  'status' : { 'resolved' : null } |
    { 'open' : null } |
    { 'inProgress' : null },
  'description' : string,
  'reporterId' : UserId,
  'timestamp' : bigint,
  'category' : string,
  'severity' : Severity,
  'photo' : [] | [ExternalBlob],
  'location' : Location,
}
export interface Location {
  'region' : string,
  'latitude' : number,
  'longitude' : number,
}
export interface Notification {
  'id' : bigint,
  'userId' : UserId,
  'read' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export interface RecoveryProgress {
  'region' : string,
  'pendingNeeds' : string,
  'overallPercentage' : bigint,
  'infrastructure' : bigint,
  'services' : bigint,
  'population' : bigint,
}
export interface ResourceInventory {
  'vehicles' : bigint,
  'food' : bigint,
  'medicine' : bigint,
  'personnel' : bigint,
  'water' : bigint,
}
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface TaskAssignment {
  'id' : TaskId,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'inProgress' : null },
  'incidentId' : IncidentId,
  'assignedTo' : UserId,
  'resourcesAllocated' : string,
  'timestamp' : bigint,
}
export type TaskId = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'contactInfo' : string,
  'name' : string,
  'role' : UserRole,
  'location' : Location,
}
export type UserRole = { 'admin' : null } |
  { 'citizen' : null } |
  { 'volunteer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Volunteer {
  'code' : string,
  'name' : string,
  'email' : string,
  'approved' : boolean,
  'phone' : string,
}
export interface VolunteerMessage { 'message' : string, 'recipientId' : UserId }
export interface _SERVICE {
  'addEmergencyContact' : ActorMethod<[string, string, string], undefined>,
  'addNotification' : ActorMethod<[UserId, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignTask' : ActorMethod<[IncidentId, UserId, string], TaskId>,
  'clearVolunteerMessage' : ActorMethod<[UserId], undefined>,
  'createAlert' : ActorMethod<
    [Location, string, Severity, string, Array<string>],
    AlertId
  >,
  'fetchVolunteerMessage' : ActorMethod<[], [] | [VolunteerMessage]>,
  'getActiveTasks' : ActorMethod<[], Array<TaskAssignment>>,
  'getAlertsByRegion' : ActorMethod<[string], Array<Alert>>,
  'getAllAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllIncidentReports' : ActorMethod<[], Array<IncidentReport>>,
  'getAllRecoveryProgress' : ActorMethod<[], Array<[string, RecoveryProgress]>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'getCallerAssignedTasks' : ActorMethod<[], Array<TaskAssignment>>,
  'getCallerIncidentReports' : ActorMethod<[], Array<IncidentReport>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getEmergencyContactsByRegion' : ActorMethod<
    [string],
    Array<EmergencyContact>
  >,
  'getIncidentReport' : ActorMethod<[IncidentId], IncidentReport>,
  'getNotificationsForUser' : ActorMethod<[], Array<Notification>>,
  'getPersistentICRole' : ActorMethod<[], UserRole>,
  'getRegionRecoveryProgress' : ActorMethod<[string], RecoveryProgress>,
  'getResourceInventory' : ActorMethod<[], ResourceInventory>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getVolunteer' : ActorMethod<[string], [] | [Volunteer]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'registerCitizen' : ActorMethod<
    [string, string, string, string, Location, string],
    undefined
  >,
  'registerVolunteer' : ActorMethod<[string, string, string], string>,
  'registerWithRole' : ActorMethod<[UserRole], undefined>,
  'reportIncident' : ActorMethod<
    [Location, string, Severity, string, [] | [ExternalBlob]],
    IncidentId
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendVolunteerMessage' : ActorMethod<[UserId, string], undefined>,
  'updateIncidentStatus' : ActorMethod<
    [
      IncidentId,
      { 'resolved' : null } |
        { 'open' : null } |
        { 'inProgress' : null },
    ],
    undefined
  >,
  'updateRecoveryProgress' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, string],
    undefined
  >,
  'updateResourceInventory' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updateTaskStatus' : ActorMethod<
    [
      TaskId,
      { 'pending' : null } |
        { 'completed' : null } |
        { 'inProgress' : null },
    ],
    undefined
  >,
  'updateVolunteerApproval' : ActorMethod<[string, boolean], undefined>,
  'validateCitizenLogin' : ActorMethod<[string, string], boolean>,
  'validateVolunteerLogin' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];