/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    region: string;
    latitude: number;
    longitude: number;
}
export interface VolunteerMessage {
    message: string;
    recipientId: UserId;
}
export type IncidentId = bigint;
export type AlertId = bigint;
export interface EmergencyContact {
    region: string;
    contactInfo: string;
    name: string;
}
export interface IncidentReport {
    id: IncidentId;
    status: Variant_resolved_open_inProgress;
    description: string;
    reporterId: UserId;
    timestamp: bigint;
    category: string;
    severity: Severity;
    photo?: ExternalBlob;
    location: Location;
}
export type UserId = Principal;
export interface TaskAssignment {
    id: TaskId;
    status: Variant_pending_completed_inProgress;
    incidentId: IncidentId;
    assignedTo: UserId;
    resourcesAllocated: string;
    timestamp: bigint;
}
export type TaskId = bigint;
export interface Notification {
    id: bigint;
    userId: UserId;
    read: boolean;
    message: string;
    timestamp: bigint;
}
export interface ResourceInventory {
    vehicles: bigint;
    food: bigint;
    medicine: bigint;
    personnel: bigint;
    water: bigint;
}
export interface RecoveryProgress {
    region: string;
    pendingNeeds: string;
    overallPercentage: bigint;
    infrastructure: bigint;
    services: bigint;
    population: bigint;
}
export interface Volunteer {
    code: string;
    name: string;
    email: string;
    approved: boolean;
    phone: string;
}
export interface Alert {
    id: AlertId;
    affectedAreas: Array<string>;
    message: string;
    timestamp: bigint;
    category: string;
    severity: Severity;
    location: Location;
}
export interface UserProfile {
    id: UserId;
    contactInfo: string;
    name: string;
    role: UserRole;
    location: Location;
}
export enum Severity {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    citizen = "citizen",
    volunteer = "volunteer"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_completed_inProgress {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum Variant_resolved_open_inProgress {
    resolved = "resolved",
    open = "open",
    inProgress = "inProgress"
}
export interface backendInterface {
    addEmergencyContact(name: string, region: string, contactInfo: string): Promise<void>;
    addNotification(userId: UserId, message: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignTask(incidentId: IncidentId, assignedTo: UserId, resourcesAllocated: string): Promise<TaskId>;
    clearVolunteerMessage(recipientId: UserId): Promise<void>;
    createAlert(location: Location, message: string, severity: Severity, category: string, affectedAreas: Array<string>): Promise<AlertId>;
    fetchVolunteerMessage(): Promise<VolunteerMessage | null>;
    getActiveTasks(): Promise<Array<TaskAssignment>>;
    getAlertsByRegion(region: string): Promise<Array<Alert>>;
    getAllAlerts(): Promise<Array<Alert>>;
    getAllIncidentReports(): Promise<Array<IncidentReport>>;
    getAllRecoveryProgress(): Promise<Array<[string, RecoveryProgress]>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getAllVolunteers(): Promise<Array<Volunteer>>;
    getCallerAssignedTasks(): Promise<Array<TaskAssignment>>;
    getCallerIncidentReports(): Promise<Array<IncidentReport>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getEmergencyContactsByRegion(region: string): Promise<Array<EmergencyContact>>;
    getIncidentReport(incidentId: IncidentId): Promise<IncidentReport>;
    getNotificationsForUser(): Promise<Array<Notification>>;
    getPersistentICRole(): Promise<UserRole>;
    getRegionRecoveryProgress(region: string): Promise<RecoveryProgress>;
    getResourceInventory(): Promise<ResourceInventory>;
    getUserProfile(user: UserId): Promise<UserProfile | null>;
    getVolunteer(email: string): Promise<Volunteer | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    registerCitizen(name: string, email: string, password: string, region: string, location: Location, contactInfo: string): Promise<void>;
    registerVolunteer(name: string, email: string, phone: string): Promise<string>;
    registerWithRole(role: UserRole): Promise<void>;
    reportIncident(location: Location, description: string, severity: Severity, category: string, photo: ExternalBlob | null): Promise<IncidentId>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendVolunteerMessage(recipientId: UserId, message: string): Promise<void>;
    updateIncidentStatus(incidentId: IncidentId, newStatus: Variant_resolved_open_inProgress): Promise<void>;
    updateRecoveryProgress(region: string, infrastructure: bigint, services: bigint, population: bigint, overallPercentage: bigint, pendingNeeds: string): Promise<void>;
    updateResourceInventory(food: bigint, water: bigint, medicine: bigint, vehicles: bigint, personnel: bigint): Promise<void>;
    updateTaskStatus(taskId: TaskId, newStatus: Variant_pending_completed_inProgress): Promise<void>;
    updateVolunteerApproval(email: string, approved: boolean): Promise<void>;
    validateCitizenLogin(email: string, password: string): Promise<boolean>;
    validateVolunteerLogin(email: string, code: string): Promise<boolean>;
}
import type { Alert as _Alert, AlertId as _AlertId, ExternalBlob as _ExternalBlob, IncidentId as _IncidentId, IncidentReport as _IncidentReport, Location as _Location, Severity as _Severity, TaskAssignment as _TaskAssignment, TaskId as _TaskId, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, Volunteer as _Volunteer, VolunteerMessage as _VolunteerMessage } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEmergencyContact(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmergencyContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmergencyContact(arg0, arg1, arg2);
            return result;
        }
    }
    async addNotification(arg0: UserId, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async assignTask(arg0: IncidentId, arg1: UserId, arg2: string): Promise<TaskId> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTask(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTask(arg0, arg1, arg2);
            return result;
        }
    }
    async clearVolunteerMessage(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearVolunteerMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearVolunteerMessage(arg0);
            return result;
        }
    }
    async createAlert(arg0: Location, arg1: string, arg2: Severity, arg3: string, arg4: Array<string>): Promise<AlertId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(arg0, arg1, to_candid_Severity_n3(this.uploadFile, this.downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(arg0, arg1, to_candid_Severity_n3(this.uploadFile, this.downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async fetchVolunteerMessage(): Promise<VolunteerMessage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchVolunteerMessage();
                return from_candid_opt_n5(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchVolunteerMessage();
            return from_candid_opt_n5(this.uploadFile, this.downloadFile, result);
        }
    }
    async getActiveTasks(): Promise<Array<TaskAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTasks();
                return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTasks();
            return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAlertsByRegion(arg0: string): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertsByRegion(arg0);
                return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertsByRegion(arg0);
            return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAlerts();
                return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAlerts();
            return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllIncidentReports(): Promise<Array<IncidentReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIncidentReports();
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIncidentReports();
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllRecoveryProgress(): Promise<Array<[string, RecoveryProgress]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecoveryProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecoveryProgress();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllVolunteers(): Promise<Array<Volunteer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVolunteers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVolunteers();
            return result;
        }
    }
    async getCallerAssignedTasks(): Promise<Array<TaskAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAssignedTasks();
                return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAssignedTasks();
            return from_candid_vec_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerIncidentReports(): Promise<Array<IncidentReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerIncidentReports();
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerIncidentReports();
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getEmergencyContactsByRegion(arg0: string): Promise<Array<EmergencyContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyContactsByRegion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyContactsByRegion(arg0);
            return result;
        }
    }
    async getIncidentReport(arg0: IncidentId): Promise<IncidentReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidentReport(arg0);
                return from_candid_IncidentReport_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidentReport(arg0);
            return from_candid_IncidentReport_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getNotificationsForUser(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsForUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsForUser();
            return result;
        }
    }
    async getPersistentICRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersistentICRole();
                return from_candid_UserRole_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersistentICRole();
            return from_candid_UserRole_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRegionRecoveryProgress(arg0: string): Promise<RecoveryProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegionRecoveryProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegionRecoveryProgress(arg0);
            return result;
        }
    }
    async getResourceInventory(): Promise<ResourceInventory> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourceInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourceInventory();
            return result;
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getVolunteer(arg0: string): Promise<Volunteer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteer(arg0);
                return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteer(arg0);
            return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async registerCitizen(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Location, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCitizen(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCitizen(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async registerVolunteer(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVolunteer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVolunteer(arg0, arg1, arg2);
            return result;
        }
    }
    async registerWithRole(arg0: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWithRole(to_candid_UserRole_n30(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWithRole(to_candid_UserRole_n30(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async reportIncident(arg0: Location, arg1: string, arg2: Severity, arg3: string, arg4: ExternalBlob | null): Promise<IncidentId> {
        if (this.processError) {
            try {
                const result = await this.actor.reportIncident(arg0, arg1, to_candid_Severity_n3(this.uploadFile, this.downloadFile, arg2), arg3, await to_candid_opt_n32(this.uploadFile, this.downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportIncident(arg0, arg1, to_candid_Severity_n3(this.uploadFile, this.downloadFile, arg2), arg3, await to_candid_opt_n32(this.uploadFile, this.downloadFile, arg4));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async sendVolunteerMessage(arg0: UserId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendVolunteerMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendVolunteerMessage(arg0, arg1);
            return result;
        }
    }
    async updateIncidentStatus(arg0: IncidentId, arg1: Variant_resolved_open_inProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncidentStatus(arg0, to_candid_variant_n36(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncidentStatus(arg0, to_candid_variant_n36(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateRecoveryProgress(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecoveryProgress(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecoveryProgress(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateResourceInventory(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResourceInventory(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResourceInventory(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateTaskStatus(arg0: TaskId, arg1: Variant_pending_completed_inProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_variant_n37(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_variant_n37(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateVolunteerApproval(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVolunteerApproval(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVolunteerApproval(arg0, arg1);
            return result;
        }
    }
    async validateCitizenLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCitizenLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCitizenLogin(arg0, arg1);
            return result;
        }
    }
    async validateVolunteerLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateVolunteerLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateVolunteerLogin(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Alert_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n12(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_IncidentReport_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentReport): Promise<IncidentReport> {
    return await from_candid_record_n17(uploadFile, downloadFile, value);
}
function from_candid_Severity_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n14(uploadFile, downloadFile, value);
}
function from_candid_TaskAssignment_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskAssignment): TaskAssignment {
    return from_candid_record_n8(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(uploadFile, downloadFile, value);
}
function from_candid_UserRole__1_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n28(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(uploadFile, downloadFile, value);
}
async function from_candid_opt_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Volunteer]): Volunteer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VolunteerMessage]): VolunteerMessage | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AlertId;
    affectedAreas: Array<string>;
    message: string;
    timestamp: bigint;
    category: string;
    severity: _Severity;
    location: _Location;
}): {
    id: AlertId;
    affectedAreas: Array<string>;
    message: string;
    timestamp: bigint;
    category: string;
    severity: Severity;
    location: Location;
} {
    return {
        id: value.id,
        affectedAreas: value.affectedAreas,
        message: value.message,
        timestamp: value.timestamp,
        category: value.category,
        severity: from_candid_Severity_n13(uploadFile, downloadFile, value.severity),
        location: value.location
    };
}
async function from_candid_record_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _IncidentId;
    status: {
        resolved: null;
    } | {
        open: null;
    } | {
        inProgress: null;
    };
    description: string;
    reporterId: _UserId;
    timestamp: bigint;
    category: string;
    severity: _Severity;
    photo: [] | [_ExternalBlob];
    location: _Location;
}): Promise<{
    id: IncidentId;
    status: Variant_resolved_open_inProgress;
    description: string;
    reporterId: UserId;
    timestamp: bigint;
    category: string;
    severity: Severity;
    photo?: ExternalBlob;
    location: Location;
}> {
    return {
        id: value.id,
        status: from_candid_variant_n18(uploadFile, downloadFile, value.status),
        description: value.description,
        reporterId: value.reporterId,
        timestamp: value.timestamp,
        category: value.category,
        severity: from_candid_Severity_n13(uploadFile, downloadFile, value.severity),
        photo: record_opt_to_undefined(await from_candid_opt_n19(uploadFile, downloadFile, value.photo)),
        location: value.location
    };
}
function from_candid_record_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    contactInfo: string;
    name: string;
    role: _UserRole;
    location: _Location;
}): {
    id: UserId;
    contactInfo: string;
    name: string;
    role: UserRole;
    location: Location;
} {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        name: value.name,
        role: from_candid_UserRole_n24(uploadFile, downloadFile, value.role),
        location: value.location
    };
}
function from_candid_record_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        inProgress: null;
    };
    incidentId: _IncidentId;
    assignedTo: _UserId;
    resourcesAllocated: string;
    timestamp: bigint;
}): {
    id: TaskId;
    status: Variant_pending_completed_inProgress;
    incidentId: IncidentId;
    assignedTo: UserId;
    resourcesAllocated: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n9(uploadFile, downloadFile, value.status),
        incidentId: value.incidentId,
        assignedTo: value.assignedTo,
        resourcesAllocated: value.resourcesAllocated,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): Severity {
    return "low" in value ? Severity.low : "high" in value ? Severity.high : "critical" in value ? Severity.critical : "medium" in value ? Severity.medium : value;
}
function from_candid_variant_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    open: null;
} | {
    inProgress: null;
}): Variant_resolved_open_inProgress {
    return "resolved" in value ? Variant_resolved_open_inProgress.resolved : "open" in value ? Variant_resolved_open_inProgress.open : "inProgress" in value ? Variant_resolved_open_inProgress.inProgress : value;
}
function from_candid_variant_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    citizen: null;
} | {
    volunteer: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "citizen" in value ? UserRole.citizen : "volunteer" in value ? UserRole.volunteer : value;
}
function from_candid_variant_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): Variant_pending_completed_inProgress {
    return "pending" in value ? Variant_pending_completed_inProgress.pending : "completed" in value ? Variant_pending_completed_inProgress.completed : "inProgress" in value ? Variant_pending_completed_inProgress.inProgress : value;
}
function from_candid_vec_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n11(uploadFile, downloadFile, x));
}
async function from_candid_vec_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncidentReport>): Promise<Array<IncidentReport>> {
    return await Promise.all(value.map(async (x)=>await from_candid_IncidentReport_n16(uploadFile, downloadFile, x)));
}
function from_candid_vec_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n22(uploadFile, downloadFile, x));
}
function from_candid_vec_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskAssignment>): Array<TaskAssignment> {
    return value.map((x)=>from_candid_TaskAssignment_n7(uploadFile, downloadFile, x));
}
async function to_candid_ExternalBlob_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_Severity_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n4(uploadFile, downloadFile, value);
}
function to_candid_UserProfile_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n35(uploadFile, downloadFile, value);
}
function to_candid_UserRole__1_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n31(uploadFile, downloadFile, value);
}
async function to_candid_opt_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n33(uploadFile, downloadFile, value));
}
function to_candid_record_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: UserId;
    contactInfo: string;
    name: string;
    role: UserRole;
    location: Location;
}): {
    id: _UserId;
    contactInfo: string;
    name: string;
    role: _UserRole;
    location: _Location;
} {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        name: value.name,
        role: to_candid_UserRole_n30(uploadFile, downloadFile, value.role),
        location: value.location
    };
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    citizen: null;
} | {
    volunteer: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.citizen ? {
        citizen: null
    } : value == UserRole.volunteer ? {
        volunteer: null
    } : value;
}
function to_candid_variant_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_resolved_open_inProgress): {
    resolved: null;
} | {
    open: null;
} | {
    inProgress: null;
} {
    return value == Variant_resolved_open_inProgress.resolved ? {
        resolved: null
    } : value == Variant_resolved_open_inProgress.open ? {
        open: null
    } : value == Variant_resolved_open_inProgress.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_inProgress): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == Variant_pending_completed_inProgress.pending ? {
        pending: null
    } : value == Variant_pending_completed_inProgress.completed ? {
        completed: null
    } : value == Variant_pending_completed_inProgress.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == Severity.low ? {
        low: null
    } : value == Severity.high ? {
        high: null
    } : value == Severity.critical ? {
        critical: null
    } : value == Severity.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
